### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by andrewrynhard** [comment]
Thanks for the PR @tariq1890. If you could please commit with the `-s` flag to sign off on this, that would be great!

**Comment by andrewrynhard** [comment]
Also the commit format should be a [conventional commit](https://www.conventionalcommits.org/en/v1.0.0-beta.3/). Look at .conform.yaml in the root of the repo to see a list of valid scopes and types. As some guidance I would commit this as something like `docs: fix typos in README.md`

**Comment by tariq1890** [comment]
@andrewrynhard Got it. I did this from the UI. Let me file a new one from my workspace instead.

**Comment by tariq1890** [comment]
Closing in favour of #370

**Pull request closed without merging**
