### PR TITLE
docs: properly wrap layouts in html/body tags

### PR DESCRIPTION
**Pull request by remyabel**
Signed-off-by: Tommy Nguyen <remyabel@gmail.com>

All documents need `<html>` tags. Also, the rest of the page needs to be wrapped in `<body>` which was in the wrong location.

### CODE REVIEW

**Comment by andrewrynhard** [comment]
@remyabel It isn't documented, but you will need to do a `make docs` to generate the HTML. We have been discussing something like https://www.netlify.com so that people don't have to do this step, but have not had the time to implement it. We are open to other ideas here as well if you have an opinion 👍 .

**Comment by remyabel** [comment]
Roger, I am working on that right now. I was installing the dependencies.

**Comment by remyabel** [comment]
`make docs` seems to be failing here:

```
#43 [base 23/24] RUN go mod download
#43       digest: sha256:f4a46307fe93887723c3115f5eeb67191cca2bd4b67f59d8b1ec3784ecf33719
#43         name: "[base 23/24] RUN go mod download"
#43      started: 2019-02-23 19:21:32.496373699 +0000 UTC
#43    completed: 2019-02-23 19:21:32.913369179 +0000 UTC
#43     duration: 416.99548ms
#43        error: "executor failed running [/toolchain/bin/bash -c go mod download]: exit code: 139"

error: failed to solve: rpc error: code = Unknown desc = executor failed running [/toolchain/bin/bash -c go mod download]: exit code: 139
```

Are there instructions somewhere on how to get setup?

**Comment by andrewrynhard** [comment]
That is an unfortunate bug: https://github.com/autonomy/talos/issues/373.

You might be able to workaround it. That target is just convenience for generating the docs: https://github.com/autonomy/talos/blob/master/Dockerfile#L223-L231

You could execute this Hugo commands yourself. If worse comes to worse, I can merge and follow up with a PR.

**Comment by remyabel** [comment]
OK done.

> We have been discussing something like https://www.netlify.com so that people don't have to do this step, but have not had the time to implement it.

I read in another issue that you are using Github Pages. If you're still doing that, Travis has a [pages provider](https://docs.travis-ci.com/user/deployment/pages/) that allows you to automatically write the built files to a `gh-pages` branch.

**Comment by andrewrynhard** [comment]
> Travis has a [pages provider](https://docs.travis-ci.com/user/deployment/pages/) that allows you to automatically write the built files to a `gh-pages` branch.

:D We are actually discussing moving off of Travis as well. Things are moving fast lately.

**Pull request merged**
